theme: minima
title: Logan Kristi McHenry-Kroetch
author: Logan McHenry-Kroetch
email: logan.mchenrykroetch@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Logan McHenry-Kroetch's Portfolio / Resume

# social links
# twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  loganmchenry # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
